version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: olymptracker-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://olimp_user:olimp_password@127.0.0.1:5432/olimp_db?schema=public
      - PORT=3001
    networks:
      - default

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: olymptracker-client
    restart: always
    ports:
      - "3000:80" # Serving static files via Nginx or similar (for Docker deployments)
    depends_on:
      - server
    networks:
      - default

networks:
  default:
